Recall De Morgan's laws,
$${\overline {A\cup B}}={\overline {A}}\cap {\overline {B}}$$
$${\overline {A\cap B}}={\overline {A}}\cup {\overline {B}}$$

then we can build up basic logic operations based on NAND:
- AND:  $$ AB=\overline { {\overline {AB}} \cdot {\overline {AB}} }$$
- OR:  $$ A+B=\overline { {\overline {AA}} \cdot {\overline {BB}} }$$
- NOT:  $$ {\overline {A}}= {\overline {AA}} $$

In [34]:
# Define basic logic operations based on NAND operation
def NAND(A,B):
    if (A==1 and B==1) :
        return 0
    else:
        return 1

def usrAND(A,B):
    return NAND(NAND(A,B),NAND(A,B))

def usrOR(A,B):
    return NAND(NAND(A,A),NAND(B,B))

def usrNOT(A):
    return NAND(A,A)

## Code used to test three basic logic functoins
def testFunc():
    a=[0,1]
    b=[0,1]
    for A in a:
        for B in b:
            print("A=%i, B=%i" %(A,B))
            print("AND: %i" %(usrAND(A,B)))
            print("OR: %i" %(usrOR(A,B)))
            print("NOT A: %i" %(usrNOT(A)))
## Test passed
#testFunc()

### Half Adder
![Image of HalfAdder](https://www.elprocus.com/wp-content/uploads/2014/12/Half-Addder.jpg)

### Truth Table of Half Adder
![Image of HalfAdder Truth Table](https://www.elprocus.com/wp-content/uploads/2014/12/Half-Addder-Truth-Table.jpg)

### Full Adder
![Image of HalfAdder](https://www.elprocus.com/wp-content/uploads/2014/12/Full-Adder.jpg)

### Truth Table of Full Adder
![Image of FullAdder Truth Table](https://www.elprocus.com/wp-content/uploads/2014/12/Full-Adder-Truth-Table.jpg)

### Full adder design using half adder
![Image of Full Adder Design](https://www.elprocus.com/wp-content/uploads/2014/12/Full-Adder-by-Half-Adders.jpg)

In [35]:
# from IPython.display import Image
# from IPython.core.display import HTML 
# Image(url= "https://www.elprocus.com/wp-content/uploads/2014/12/Full-Adder.jpg")

In [36]:
import numpy as np

def bin2dec(intList):
    '''Test function, transform number in binary form to decimal system'''
    number = 0
    N = len(intList)
    for i in range(1,N+1):
        number = number + intList[i-1]*2**(N-i)
    return number

def halfAdder(A,B):
    '''Define half-addition, will return result in form of one sum bit and one extra carry bit '''
    if A != 1 and A !=0:
        raise ValueError("Not a valid binary bit input")
    if B != 1 and B !=0:
        raise ValueError("Not a valid binary bit input")
    sum_bit = usrOR(usrAND(A,usrNOT(B)),usrAND(usrNOT(A),B))
    carry_bit = usrAND(A,B)
    return sum_bit, carry_bit

def fullAdder(A,B,C):
    '''Define full-addition, take in two bits to be added and one more carry bit, return sum bit and carry bit '''
    if A != 1 and A !=0:
        raise ValueError("Not a valid binary bit input")
    if B != 1 and B !=0:
        raise ValueError("Not a valid binary bit input")
    if C != 1 and C !=0:
        raise ValueError("Not a valid binary bit input")
    mid_sum, mid_carry_1 = halfAdder(A,B)
    sum_bit, mid_carry_2 = halfAdder(mid_sum, C)
    carry_bit = usrOR(mid_carry_1,mid_carry_2)
    return sum_bit, carry_bit

# fullAdder test code
# for i in range(2):
#     for j in range(2):
#         for k in range(2):
#             print(fullAdder(i,j,k))

### Carry lookahead adder based on full adder
![Image of lookahead adder](https://www.nandland.com/vhdl/modules/images/carry-lookahead-adder-4-bit.png)

In [38]:
N = 8
# Generate two random binary numbers with N digits
intA = np.random.randint(0,2,N)
intB = np.random.randint(0,2,N)
# Initialize array to store addition result, all the elements in list will be zero
intC = np.random.randint(0,1,N+1)

## Connect full adder in series to realize multiple bit addition
intC[-1], carry_bit = fullAdder(intA[-1],intB[-1],0)
for i in range(1,len(intA)):
    intC[-1-i], carry_bit = fullAdder(intA[-1-i],intB[-1-i],carry_bit)
intC[0] = carry_bit

print("  "+str(intA))
print("  "+str(intB))
print(intC)

numA = bin2dec(intA)
numB = bin2dec(intB)
numC = bin2dec(intC)
print("%i + %i = %i" %(numA,numB,numC))

  [0 1 0 0 0 1 0 0]
  [0 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 0 0]
68 + 68 = 136


In [ ]:
## Obsolete code


# import numpy as np

# def bin2dec(intList):
#     '''Test function, transform number in binary form to decimal system'''
#     number = 0
#     N = len(intList)
#     for i in range(1,N+1):
#         number = number + intList[i-1]*2**(N-i)
#     return number

# def oneBitAdd(A,B):
#     '''Define one bit addition, will return result in form of one bit and one extra bit in register'''
#     result = usrOR(usrAND(A,usrNOT(B)),usrAND(usrNOT(A),B))
#     register = usrAND(A,B)
#     return register, result

# def multiAdd(AList,BList):
#     N = len(AList)
#     CList = np.random.randint(0,1,N+1)
#     register = 0
#     for i in range(len(AList)):
#         A = AList[-i-1]
#         B = BList[-i-1]
#         midReg_1, C = oneBitAdd(A,B)
#         midReg_2, C = oneBitAdd(C,register)
#         null, register = oneBitAdd(midReg_1,midReg_2)
#         CList[-i-1] = int(C)
#     CList[0] = int(register)
#     return CList

# N = 5
# intA = np.random.randint(0,2,N)
# intB = np.random.randint(0,2,N)
# #intB = np.random.randint(1,2,N) # All the elements in list will be one

# intC = multiAdd(intA,intB)
# print("  "+str(intA))
# print("  "+str(intB))
# print(intC)

# numA = bin2dec(intA)
# numB = bin2dec(intB)
# numC = bin2dec(intC)
# print("%i + %i = %i" %(numA,numB,numC))